version: "3"
services:
  lv-inspection-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=CapeElectricSoftware@2021
      - MYSQL_DATABASE=lv_safety_verification
    ports:
      - 3306:3306