CREATE DATABASE lv_safety_verification;
use lv_safety_verification;

create table USERS 
(user_id integer not null, 
user_active boolean,
creation_date datetime,
email varchar(255),
first_name varchar(255),
last_name varchar(255),
password varchar(255),
user_role varchar(255),
user_exist boolean,
user_name varchar(255),
user_type varchar(255),
updated_date datetime,
primary key (user_id));

create table APPLICATIONTYPES(id integer not null, application varchar(255), code varchar(20), primary key(id),application_Name varchar(10));

insert into APPLICATIONTYPES values (1,'Verification Of LV Systems (IEC 60364-6)', 'LV Systems','LV');
insert into APPLICATIONTYPES values (2,'Verification Of HV Systems (up to 33 kV) (IEC 61936-1)', 'HV Systems','HV');
insert into APPLICATIONTYPES values (3,'Lightning Protection Conformity Assessment, Risk Assessment, Inspection And Maintenance (IEC 62305-3 & 4)', 'Risk Assessment', 'LPS');
insert into APPLICATIONTYPES values (4,'EMC Assessment Of An Installation (IEC 61000-5-1)', 'EMC Assessment','EMC');
insert into APPLICATIONTYPES values (5,'Failure Analysis Of Electronic Systems', 'Failure Analysis','FAS');
insert into APPLICATIONTYPES values (6,'Conformity And Project Analysis', 'Conformity Project','CPA');


insert into APPLICATIONTYPES values (5,'Failure analysis of electronic systems'
insert into APPLICATIONTYPES values (6,'Conformity and project analysis'


CREATE TABLE COMPANY_TABLE (
    COMPANY_ID INT AUTO_INCREMENT ,
    COMPANY_CODE VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL ,
    CLIENT_NAME VARCHAR(255)NOT NULL UNIQUE,
	IN_ACTIVE BIT,
    CREATED_BY VARCHAR(255) NOT NULL,
    UPDATED_BY VARCHAR(255) NOT NULL,
    CREATED_DATE datetime NOT NULL,    
    UPDATED_DATE datetime NOT NULL,
    CONSTRAINT PK_COMPANY_ID PRIMARY KEY(COMPANY_ID)
);
CREATE TABLE DEPARTMENT_TABLE (
    DEPARTMENT_ID INT AUTO_INCREMENT,
    COMPANY_ID INT,
    DEPARTMENT_CODE VARCHAR(255)NOT NULL,
	USER_NAME VARCHAR(255)NOT NULL,
	CLIENT_NAME VARCHAR(255) NOT NULL,
	DEPARTMENT_NAME VARCHAR(255)NOT NULL UNIQUE,
	CREATED_BY VARCHAR(255)NOT NULL,
    UPDATED_BY VARCHAR(255)NOT NULL,
    CREATED_DATE datetime NOT NULL,    
    UPDATED_DATE datetime NOT NULL,
	CONSTRAINT PK_DEPARTMENT_ID PRIMARY KEY(DEPARTMENT_ID),
    CONSTRAINT FK_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY_TABLE(COMPANY_ID) ON DELETE CASCADE
);

CREATE TABLE SITE_TABLE (
    SITE_ID INT AUTO_INCREMENT,
	DEPARTMENT_ID INT,
	SITE_CODE VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255),
 	CLIENT_NAME VARCHAR(255),
	DEPARTMENT_NAME VARCHAR(255),
	SITE VARCHAR(255) NOT NULL,
	ADDRESSLINE_1 VARCHAR(255) NOT NULL,
	ADDRESSLINE_2 VARCHAR(255) NOT NULL,
	LAND_MARK VARCHAR(255) NOT NULL,
	CITY VARCHAR(255) NOT NULL,
	STATE VARCHAR(255) NOT NULL,
	COUNTRY VARCHAR(255) NOT NULL,
	ZIP_CODE VARCHAR(255) NOT NULL,
	CREATED_BY VARCHAR(255) NOT NULL,
    UPDATED_BY VARCHAR(255) NOT NULL,
    CREATED_DATE datetime NOT NULL,    
    UPDATED_DATE datetime NOT NULL,
	CONSTRAINT PK_SITE_ID PRIMARY KEY(SITE_ID),
    CONSTRAINT FK_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT_TABLE(DEPARTMENT_ID) ON DELETE CASCADE
);

CREATE TABLE SITE_PERSON_TABLE(
	 PERSON_ID INT AUTO_INCREMENT,
	 SITE_ID INT,
	 IN_ACTIVE BIT,
	 PERSON_INCHARGE VARCHAR(255),
	 E_mail VARCHAR(255)not null,
	 DESIGNATION VARCHAR(255),
	 CONTACT_NO VARCHAR(255),
	 CONSTRAINT PK_PERSON_ID PRIMARY KEY(PERSON_ID),
	 CONSTRAINT FK_SITE_ID FOREIGN KEY (SITE_ID) REFERENCES SITE_TABLE(SITE_ID) ON DELETE CASCADE
 );
CREATE TABLE COUNTRY_TABLE (COUNTRY_ID INTEGER NOT NULL, NAME VARCHAR(255), CODE VARCHAR(255), CONSTRAINT PK_COUNTRY_ID PRIMARY KEY(COUNTRY_ID));
CREATE TABLE STATE_TABLE (STATE_ID INT NOT NULL, COUNTRY_ID INT, NAME VARCHAR(255), CODE VARCHAR(255),
CONSTRAINT PK_STATE_ID PRIMARY KEY(STATE_ID),
CONSTRAINT FK_COUNTRY_ID FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY_TABLE(COUNTRY_ID) ON DELETE CASCADE);

insert into COUNTRY_TABLE values (1, 'INDIA', 'IND');
insert into COUNTRY_TABLE values (2, 'UNITED STATES OF AMERICA', 'USA');
insert into COUNTRY_TABLE values (3, 'BANGLADESH', 'BGL');
insert into COUNTRY_TABLE values (4, 'SRILANKA', 'SRI');
insert into COUNTRY_TABLE values (5, 'UNITED KINGDOM', 'UK');
insert into COUNTRY_TABLE values (6, 'PAKISTAN', 'PAK');
insert into COUNTRY_TABLE values (7, 'AFGANISTAN', 'AFG');
insert into COUNTRY_TABLE values (8, 'MALDIVES', 'MDV');
insert into COUNTRY_TABLE values (9, 'UNITED ARAB EMIRATES', 'UAE');
insert into COUNTRY_TABLE values (10, 'CHINA', 'CHN');
insert into COUNTRY_TABLE values (11, 'SINGAPORE', 'SGP');
insert into COUNTRY_TABLE values (12, 'THAILAND', 'THL');
insert into COUNTRY_TABLE values (13, 'AUSTRALIA', 'AUS');
insert into COUNTRY_TABLE values (14, 'NEW ZEALAND', 'NZL');
insert into COUNTRY_TABLE values (15, 'JAPAN', 'JPN');
insert into COUNTRY_TABLE values (16, 'INDONESIA', 'INA');
insert into COUNTRY_TABLE values (17, 'MALAYSIA', 'MLY');
insert into COUNTRY_TABLE values (18, 'GERMANY', 'GNY');
insert into COUNTRY_TABLE values (19, 'FRANCE', 'FRN');
insert into COUNTRY_TABLE values (20, 'RUSSIA', 'RUS');

INSERT INTO STATE_TABLE VALUES (1,1,'Tamil Nadu','TN');
INSERT INTO STATE_TABLE VALUES (2,1,'Andhra Pradesh','AP');
INSERT INTO STATE_TABLE VALUES (3,1,'Telengana','TS');
INSERT INTO STATE_TABLE VALUES (4,1,'Karnataka','KA');
INSERT INTO STATE_TABLE VALUES (5,1,'Kerala','KL');
INSERT INTO STATE_TABLE VALUES (6,1,'Odisha','OR');
INSERT INTO STATE_TABLE VALUES (7,1,'Maharastra','MH');
INSERT INTO STATE_TABLE VALUES (8,1,'Madhya Pradesh','MP');
INSERT INTO STATE_TABLE VALUES (9,1,'Chattisgarh','CG');
INSERT INTO STATE_TABLE VALUES (10,1,'Jharkand','JD');
INSERT INTO STATE_TABLE VALUES (11,1,'Bihar','BH');
INSERT INTO STATE_TABLE VALUES (12,1,'Uttar Pradesh','UP');
INSERT INTO STATE_TABLE VALUES (13,1,'Gujarat','GU');
INSERT INTO STATE_TABLE VALUES (14,1,'Rajasthan','RJ');
INSERT INTO STATE_TABLE VALUES (15,1,'Punjab','PB');
INSERT INTO STATE_TABLE VALUES (16,1,'Haryana','HR');
INSERT INTO STATE_TABLE VALUES (17,1,'Uttarkhand','UT');
INSERT INTO STATE_TABLE VALUES (18,1,'Sikkim','SK');
INSERT INTO STATE_TABLE VALUES (19,1,'West Bengal','WB');
INSERT INTO STATE_TABLE VALUES (20,1,'Assam','AS');
INSERT INTO STATE_TABLE VALUES (21,1,'Arunachala Pradesh','AR');
INSERT INTO STATE_TABLE VALUES (22,1,'Nagaland','NG');
INSERT INTO STATE_TABLE VALUES (23,1,'Tripura','TP');
INSERT INTO STATE_TABLE VALUES (24,1,'Meghalaya','MG');
INSERT INTO STATE_TABLE VALUES (25,1,'Mizoram','MZ');
INSERT INTO STATE_TABLE VALUES (26,1,'Manipur','GU');
INSERT INTO STATE_TABLE VALUES (27,1,'Goa','GA');
INSERT INTO STATE_TABLE VALUES (28,2,'Others','OT');


---> Part_1  Basic information


CREATE TABLE REPORT_DETAILS_TABLE (
    REPORT_ID INT AUTO_INCREMENT,
	USER_NAME VARCHAR(255),
	DESCRIPTION_REPORT VARCHAR(500),
	REASON_REPORT VARCHAR(500),
	INSTALLATION_TYPE VARCHAR(255),
	DESCRIPTION_PREMISE VARCHAR(255) ,
	ESTIMATED_WIRE_AGE VARCHAR(255),
	EVIDANCE_ADDITION VARCHAR(255),
    PREVIOUS_RECORDS VARCHAR(255),
    LAST_INSPECTION VARCHAR(255),
    NEXT_INSPECTION VARCHAR(255),	
    EXTENT_INSTALLATION VARCHAR(500),
    CLIENT_DETAILS VARCHAR(500),
    INSTALLATION_DETAILS VARCHAR(500),
    VERIFICATION_DATE VARCHAR(500),  
    VERIFIED_ENGINEER VARCHAR(255),
    DESIGNATION VARCHAR(255) ,
    COMPANY VARCHAR(255),
	CREATED_BY VARCHAR(255),
    CREATED_DATE datetime,
    CONSTRAINT PK_REPORT_ID PRIMARY KEY(REPORT_ID)
 );
 
 
 
 CREATE TABLE SIGN_DETAILS_TABLE (
            SIGNATOR_ID INT AUTO_INCREMENT,
            REPORT_ID INT,
			SIGNATOR_ROLE VARCHAR(255),
			PERSON_NAME VARCHAR(255),
			PERSON_CONTACT_NO VARCHAR(255),
			PERSON_MAIL_ID VARCHAR(255),
			MANAGER_NAME VARCHAR(255),
			MANAGER_CONTACT_NO VARCHAR(255),
			MANAGER_MAIL_ID VARCHAR(255),
			COMPANY_NAME VARCHAR(255),
			ADDRESS_LINE1 VARCHAR(255),
			ADDRESS_LINE2 VARCHAR(255),
			LAND_MARK VARCHAR(255),
			STATE VARCHAR(255),
			PIN_CODE VARCHAR(255),
			COUNTRY VARCHAR(255),
			DECLARATION_DATE VARCHAR(255),
			DECLARATION_NAME VARCHAR(255),
			DECLARATION_SIGNATURE BLOB,
			CONSTRAINT PK_SIGNATOR_ID PRIMARY KEY(SIGNATOR_ID),
			CONSTRAINT FK_REPORT_ID FOREIGN KEY (REPORT_ID) REFERENCES REPORT_DETAILS_TABLE(REPORT_ID) ON DELETE CASCADE
);
 



---> Part_2 Supply characteristics and earthing arrangement API.
     ----------------------------------------------------

CREATE TABLE SUPPLY_CHARACTERISTICS_TABLE (

            SUPPLY_CHARACTERISTICS_ID INT AUTO_INCREMENT,
			SITE_ID INT,
			USER_NAME VARCHAR(255),
            MAIN_SYSTEM_EARTING VARCHAR(255),
            SYSTEM_EARTH_BNOTE VARCHAR(255),
            LIVE_CONDUCTOR_TYPE VARCHAR(255),
            LIVE_CONDUCTOR_AC VARCHAR(255),
            LIVE_CONDUCTOR_DC VARCHAR(255),
            LIVE_CONDUCTOR_BNOTE VARCHAR(255),
            MAIN_NOMINAL_VOLTAGE VARCHAR(255),
            MAIN_NOMINAL_FREQUENCY VARCHAR(255),
            MAIN_FAULT_CURRENT VARCHAR(255),
            MAIN_LOOP_IMPEDANCE VARCHAR(255),
            MAIN_CURRENT_PROTECTIVE_DEVICE VARCHAR(255),
            MAIN_RATED_CURRENT VARCHAR(255),
            MAIN_CURRENT_DISCONNECTION VARCHAR(255),
            AL_AVILABLE_SUPPLY BIT,
            AL_NUM_SUPPLY VARCHAR(255),
            MAXIMUM_DEMAND VARCHAR(255),
            MAXIMUM_LOAD VARCHAR(255),
            MEANS_EARTHING VARCHAR(255),
            ELECTORDE_TYPE VARCHAR(255),
            ELECTORDE_MATERIAL VARCHAR(255),
            NUM_LOCATION INT,
            CONDUCTOR_SIZE VARCHAR(255),
            CONDUCTOR_MATERIAL VARCHAR(255),
            CONDUCTOR_VERIFY BIT,
            BONDING_CONDUCTOR_SIZE VARCHAR(255),
            BONDING_CONDUCTOR_MATERIAL VARCHAR(255),
            BONDING_CONDUCTOR_VERIFY BIT,
            BONDING_JOINTS_TYPE VARCHAR(255),
            BONDING_NO_OF_JOINTS INT,
            EARTHING_CONDUCTOR_SIZE VARCHAR(255),
            EARTHING_CONDUCTOR_MATERIAL VARCHAR(255),
            EARTHING_CONDUCTOR_VERIFY BIT,
            EARTHING_JOINTS_TYPE VARCHAR(255),
            EARTHING_NO_OF_JOINTS INT,
            CREATED_DATE datetime,
            CONSTRAINT PK_SUPPLY_CHARACTERISTICS_ID PRIMARY KEY(SUPPLY_CHARACTERISTICS_ID)
              
);
 
CREATE TABLE SUPPLY_PARAMETERS_TABLE (

            SUPPLY_PARAMETERS_ID INT AUTO_INCREMENT,
            SUPPLY_CHARACTERISTICS_ID INT,
            AL_SYSTEM_EARTING VARCHAR(255),
            AL_SUPPLY_NO VARCHAR(255),
            AL_SUPPLY_STNAME VARCHAR(255),
            AL_SYSTEM_EARTING_BNOTE VARCHAR(255),
            AL_LIVECONDUCTOR_TYPE VARCHAR(255),
            AL_LIVECONDUCTOR_AC VARCHAR(255),
            AL_LIVECONDUCTOR_DC VARCHAR(255),
            AL_LIVECONDUCTOR_BNOTE VARCHAR(255),
             AL_NOMINAL_VOLTAGE VARCHAR(255),
            AL_NOMINAL_FREQUENCY VARCHAR(255),
            AL_FAULT_CURRENT VARCHAR(255),
            AL_LOOP_IMPEDANCE VARCHAR(255),
            AL_INSTALLED_CAPACITY VARCHAR(255),
            AL_ACTUAL_LOAD VARCHAR(255) ,
            AL_RATED_CURRNT VARCHAR(255),
            AL_CURRENT_DISCONNECTION VARCHAR(255),
            CONSTRAINT PK_SUPPLY_PARAMETERS_ID PRIMARY KEY(SUPPLY_PARAMETERS_ID),
            CONSTRAINT FK_SUPPLY_CHARACTERISTICS_ID FOREIGN KEY (SUPPLY_CHARACTERISTICS_ID) REFERENCES SUPPLY_CHARACTERISTICS_TABLE(SUPPLY_CHARACTERISTICS_ID) ON DELETE CASCADE

 );
 
  CREATE TABLE CIRCUIT_BREAKER_TABLE (
 
            CIRCUIT_BREAKER_ID INT AUTO_INCREMENT, 
            SUPPLY_CHARACTERISTICS_ID INT,
            LOCATION VARCHAR(255),
            TYPE VARCHAR(255),
			CURRENT_CURVE_TYPE VARCHAR(255),
            POLES_NO VARCHAR(255),
            CURRRENT VARCHAR(255),
            VOLTAGE VARCHAR(255),
            FUSE VARCHAR(255),
            RESIDUAL_CURRENT VARCHAR(255),
            RESIDUAL_TIME VARCHAR(255),
            CONSTRAINT PK_CIRCUIT_BREAKER_ID PRIMARY KEY(CIRCUIT_BREAKER_ID),
            CONSTRAINT FK_CIRCUIT_BREAKER_SUPPLY_CHARACTERISTICS_ID FOREIGN KEY (SUPPLY_CHARACTERISTICS_ID) REFERENCES SUPPLY_CHARACTERISTICS_TABLE(SUPPLY_CHARACTERISTICS_ID) ON DELETE CASCADE
                   
);

CREATE TABLE INSTALLATION_LOCATION_TABLE (
            INSTALLATION_LOCATION_REPORT_ID INT AUTO_INCREMENT,
            SUPPLY_CHARACTERISTICS_ID INT,
            LOCATION_NO VARCHAR(255),
            LOCATION_NAME VARCHAR(500),
            ELECTORDE_RESISTANCE_EARTH VARCHAR(500),
            ELECTORDE_RESISTANCE_GRID VARCHAR(255),
            CONSTRAINT PK_INSTALLATION_LOCATION_REPORT_ID PRIMARY KEY(INSTALLATION_LOCATION_REPORT_ID),
            CONSTRAINT FK_INSTALLATION_LOCATION_REPORTS_SUPPLY_CHARACTERISTICS_ID FOREIGN KEY (SUPPLY_CHARACTERISTICS_ID) REFERENCES SUPPLY_CHARACTERISTICS_TABLE(SUPPLY_CHARACTERISTICS_ID) ON DELETE CASCADE


 );

 CREATE TABLE BOUNDING_LOCATION_REPORTS_TABLE (
            BOUNDING_REPORT_ID INT AUTO_INCREMENT,
            SUPPLY_CHARACTERISTICS_ID INT,
			LOCATION VARCHAR(255),
			JOINT_NO VARCHAR(255),
            JOINT_RESISTANCE VARCHAR(255) ,
            CONSTRAINT PK_BOUNDING_LOCATION_REPORT_ID PRIMARY KEY(BOUNDING_REPORT_ID),
            CONSTRAINT FK_BOUNDING_LOCATION_REPORTS_SUPPLY_CHARACTERISTICS_ID FOREIGN KEY (SUPPLY_CHARACTERISTICS_ID) REFERENCES SUPPLY_CHARACTERISTICS_TABLE(SUPPLY_CHARACTERISTICS_ID) ON DELETE CASCADE


 );
 
  CREATE TABLE EARTHING_LOCATION_REPORTS_TABLE (
            EARTHING_LOCATION_REPORT_ID INT AUTO_INCREMENT,
            SUPPLY_CHARACTERISTICS_ID INT,
			LOCATION VARCHAR(255),
			JOINT_NO VARCHAR(255),
            JOINT_RESISTANCE VARCHAR(255) ,
            CONSTRAINT PK_EARTHING_LOCATION_REPORT_ID PRIMARY KEY(EARTHING_LOCATION_REPORT_ID),
            CONSTRAINT FK_EARTHING_LOCATION_REPORTS_SUPPLY_CHARACTERISTICS_ID FOREIGN KEY (SUPPLY_CHARACTERISTICS_ID) REFERENCES SUPPLY_CHARACTERISTICS_TABLE(SUPPLY_CHARACTERISTICS_ID) ON DELETE CASCADE


 );
 
 --> part_3  Periodic_inspection

CREATE TABLE IPAO_INSPECTION_TABLE (
            IPAO_INSPECTION_ID INT AUTO_INCREMENT,
            SITE_ID INT,
			USER_NAME VARCHAR(225),
            I_SERVICE_CABLE VARCHAR(10),
            I_SERVICE_FUSE VARCHAR(10),
            I_METER_DISTRIBUTOR VARCHAR(10),
            I_METER_CONSUMER VARCHAR(10),
            I_METER_EQU VARCHAR(10),
            I_ISOLATOR VARCHAR(10),
            P_EARTHING_ARRANGEMENT VARCHAR(10),
            P_ADEQUATE_ARRANGEMENT VARCHAR(10),
            P_CONNECTION_GENERATOR VARCHAR(10),
            P_COMPATIBILITY_CHARACTERISTICS VARCHAR(10),
            P_AUTOMATIC_DISCONNECT_GENERATOR VARCHAR(10),
            P_PREVENT_CONNECT_GENERATOR VARCHAR(10),
            P_ISOLATE_GENERATOR VARCHAR(10),
            A_MAIN_EARTHING VARCHAR(10),
            A_EARTH_ELECTORDE_ARRANGEMENT VARCHAR(10),
            A_EARTH_CONDUCTOR_CONNECTION VARCHAR(10),
            A_ACCESSIBILITY VARCHAR(10),
            A_MAIN_PROTECT_BONDING VARCHAR(10),
            A_ALL_PROTECT_BONDING VARCHAR(10),
            A_ALL_APPROPRIATE_LOCATION VARCHAR(10),
            A_FELV_REQUIREMENT VARCHAR(255),
            O_SELV_SYSTEM VARCHAR(255),
            O_PELV_SYSTEM VARCHAR(255),
            O_DOUBLE_INSULATION VARCHAR(255),
            O_REINFORCED_INSULATION VARCHAR(255),
            O_BASIC_ELECTRICAL_SEPARTION VARCHAR(255),
            O_INSULATION_LIVE_PARTS VARCHAR(255),
            O_BARRIERS_ENCLOSERS VARCHAR(255),
            O_OBSTACLES VARCHAR(255),
            O_PLACING_OUT_REACH VARCHAR(255),
            O_NON_CONDUCT_LOCATION VARCHAR(255),
            O_FAULT_ELECTRICAL_SEPARTION VARCHAR(255),
            O_FAULT_NON_CONDUCT_LOCATION VARCHAR(255),
            O_OPERATING_CURRENT VARCHAR(255),
            O_SUPPLEMENTARY_BONDING VARCHAR(255),
            CONSTRAINT PK_IPAO_INSPECTION_ID PRIMARY KEY(IPAO_INSPECTION_ID)
 );
 
 CREATE TABLE CONSUMER_TABLE (  
            CONSUMER_ID INT AUTO_INCREMENT,
	        IPAO_INSPECTION_ID INT,
            ACCESS_AND_WORKING VARCHAR(10),
            SECURITY_OF_FIXING VARCHAR(10),
            LIVE_PARTS_NOT_DAMAGE VARCHAR(10),
            SECURITY_OF_BARRIERS VARCHAR(10),
            SUITABILITY_OF_ENCLOSURE VARCHAR(10),
            ENCLOSURE_NOT_DAMAGED VARCHAR(10),
            PRESENCE_OF_OBSTACLES VARCHAR(10),
            PLACING_OUT_OF_CONSUMER VARCHAR(10),
            PRESENCE_MAIN_SWITCHES VARCHAR(10),
            OPERATION_MAIN_SWITCHES VARCHAR(10),
            MANUAL_CIRCUIT_BREAKERS VARCHAR(10),
            SWITCH_CAUSES_RCD VARCHAR(10),
            RCD_FAULT_PROTECTION VARCHAR(10),
            RCD_ADDITIONAL_PROTECTION VARCHAR(10),
            OVER_VOLTAGE_PROTECTION VARCHAR(10),
            INDICATION_OF_SPD VARCHAR(10),
            RCD_QUARTERLY_TEST VARCHAR(10),
            DIAGRAMS_CHARTS VARCHAR(10),
            NONSTANDARD_CABLE_COLOUR VARCHAR(10),
            AL_SUPPLY_OF_ORIGN VARCHAR(10),
            AL_SUPPLY_OF_METER VARCHAR(10),
            AL_SUPPLY_DISTRIBUTION VARCHAR(10),
            ALL_POINTS_ISOLATION VARCHAR(10),
            NEXT_INSPECTION VARCHAR(10),
            OTHER_REQUIRED_LABELLING VARCHAR(10),
            BASES_CORRECT_TYPE VARCHAR(10),
            SINGLE_POLE VARCHAR(10),
            MECHANICAL_DAMAGE VARCHAR(10),
            ELECTROMAGNETIC VARCHAR(10),
            ALL_CONDUCTOR_CON VARCHAR(10),
			CONSTRAINT PK_CONSUMER_ID PRIMARY KEY(CONSUMER_ID),
			CONSTRAINT FK_CONSUMER_IPAO_INSPECTION_ID  FOREIGN KEY (IPAO_INSPECTION_ID) REFERENCES IPAO_INSPECTION_TABLE(IPAO_INSPECTION_ID) ON DELETE CASCADE

 );
		
CREATE TABLE CIRCUIT_TABLE (      
            CIRCUIT_ID INT AUTO_INCREMENT,
		    IPAO_INSPECTION_ID INT ,
            IDENTIFICATION_CONDUCTORS VARCHAR(10),
            CABLE_INSTALLATION VARCHAR(10),
            EXAMINATION_CABLES VARCHAR(10),
            EXAMINATION_INSULATION VARCHAR(10),
            NON_SHEATHED_CABLES VARCHAR(10),
            CONTAINMENT_SYSTEMS VARCHAR(10),
            TEMPERATURE_RATING VARCHAR(10),
            CABLES_TERMINATED VARCHAR(10),
            CURRENT_CARRY_CAPACITY VARCHAR(10),
            ADEQUACY_PROTECT_DEVICES VARCHAR(10),
            PRESENCE_PROTECT_CONDUCTORS VARCHAR(10),
            CO_ORDINATION VARCHAR(10),
            WIRING_SYSTEMS VARCHAR(10),
            CABLES_CONCEAL_UNDER_FLOORS VARCHAR(10),
            OPERATING_CURRENT_CIRCUITS VARCHAR(10),
            OPERATING_CURRENT_SOCKET VARCHAR(10),
            CABLES_CONC_DEPTH VARCHAR(10),
            SECTIONS_REGARDLESS_DEPTH VARCHAR(10),
            PROVISION_FIRE_BARRIERS VARCHAR(10),
            SEPARATION_BAND VARCHAR(10),
            SEPARATION_ELECTRICAL VARCHAR(10),
            CONDITION_CIRCUIT_ACCESSORIES VARCHAR(10),
            CONDUCTOR_CORRECT_TERMINATED VARCHAR(10),
            CONDUCTOR_VISIBLE_OUTSIDE VARCHAR(10),
            CONN_LIVE_CONDUCTORS VARCHAR(10),
            ADEQUATELY_CONNECTED_ENCLOSURE VARCHAR(10),
            SUITABILITY_CIRCUIT_ACCESSORIES VARCHAR(10),
            CONDITION_ACCESSORIES VARCHAR(10),
            SINGLE_POLE_DEVICES VARCHAR(10),
            ADEQUACY_CONNECTIONS VARCHAR(10),
            ISOLATION_AND_SWITCHING VARCHAR(10),
			CONSTRAINT PK_CIRCUIT_ID PRIMARY KEY(CIRCUIT_ID),
			CONSTRAINT FK_CIRCUIT_IPAO_INSPECTION_ID  FOREIGN KEY (IPAO_INSPECTION_ID) REFERENCES IPAO_INSPECTION_TABLE(IPAO_INSPECTION_ID) ON DELETE CASCADE
);    
		
		                    
CREATE TABLE ISOLATION_CURRENT_TABLE (       
            ISOLATION_CURRENT_ID INT AUTO_INCREMENT,
	    	IPAO_INSPECTION_ID INT,
            I_PRESENCE_DEVICES VARCHAR(10),
            I_CONDITION_DEVICES VARCHAR(10),
            I_LOCATION_DEVICES VARCHAR(10),
            I_CAPABLE_SECURED VARCHAR(10),
            I_OPERATION_VERIFY VARCHAR(10),
            I_INSTALL_CIRCUIT VARCHAR(10),
            I_WARNING_LABEL VARCHAR(10),
            SW_PRESENCE_DEVICES VARCHAR(10),
            SW_CONDITION_DEVICES VARCHAR(10),
            SW_ACCEPTABLE_LOCATION VARCHAR(10),
            SW_CAPABLE_OFF_POSITION VARCHAR(10),
            SW_CORRECT_OPERATION VARCHAR(10),
            SW_CIRCUIT VARCHAR(10),
            SW_WARNING_LABEL VARCHAR(10),
            EM_SWIT_PRESENCE_DEVICES VARCHAR(10),
            EM_SWIT_CONDITION_DEVICES VARCHAR(10),
            EM_SWIT_LOCATION_DEVICES VARCHAR(10),
            EM_SWIT_OPERATION_VERIFY VARCHAR(10),
            EM_SWIT_INSTALL_CIRCUIT VARCHAR(10),
            FU_SWIT_PRESENCE_DEVICES VARCHAR(10),
            FU_SWIT_LOCATION_DEVICES VARCHAR(10),
            FU_SWIT_OPERATION_VERIFY VARCHAR(10),
            C_SUITABILITY_EQUIPMENT VARCHAR(10),
            C_ENCLOSURE_NOT_DAMAGED VARCHAR(10),
            C_SUITABILITY_ENVIRONMENT VARCHAR(10),
            C_SECURITY_FIXING VARCHAR(10),
            C_CABLE_ENTRY_HOLES VARCHAR(10),
            C_PROVISION_VOLTAGE VARCHAR(10),
            C_PROVISION_OVERLOAD VARCHAR(10),
            C_CORRECT_TYPE_LAMPS VARCHAR(10),
            C_INSULA_DISPLACEMENT_BOX VARCHAR(10),
            C_OVERHEAT_SURROUNDING VARCHAR(10),
            C_OVERHEAT_CONDUCTORS VARCHAR(10),
			CONSTRAINT PK_ISOLATION_CURRENT_ID PRIMARY KEY(ISOLATION_CURRENT_ID),
			CONSTRAINT FK_ISOLATION_IPAO_INSPECTION_ID  FOREIGN KEY (IPAO_INSPECTION_ID) REFERENCES IPAO_INSPECTION_TABLE(IPAO_INSPECTION_ID) ON DELETE CASCADE

);

--> Part_4 TestingAPI

CREATE TABLE TESTING_TABLE (
				TESTING_ID INT AUTO_INCREMENT,
				SITE_ID INT,
				USER_NAME VARCHAR(225),
				TEST_ENGINEER_NAME VARCHAR(225),
				DATE VARCHAR(225),
				DETAILS_TEST_INSTRUMENT VARCHAR(225),
				CONTINUITY VARCHAR(225),
				INSULATION_RESISANCE VARCHAR(225),
				IMPEDANCE VARCHAR(225),
				RCD VARCHAR(225),
				EARTH_ELECTRODE_RESISTANCE VARCHAR(225),
				DESIGNATION  VARCHAR(225),
				COMPANY_NAME  VARCHAR(225),        
				CREATED_DATE DATETIME,
				CONSTRAINT PK_TESTING_ID PRIMARY KEY(TESTING_ID)
              
);

CREATE TABLE TESTING_DISTRIBUTION_TABLE (
                DISTRIBUTION_ID INT AUTO_INCREMENT,
				TESTING_ID INT,
                DISTRIBUTION_BOARD_DETAILS VARCHAR(225),
				REFERANCE VARCHAR(225),
				LOCATION VARCHAR(225),
				CORRECT_SUPPLY_POLARITY VARCHAR(225),
				NUM_OUTPUT_CIRCUITS_USE VARCHAR(225),
				RATINGS_AMPS VARCHAR(225),
				NUM_OUTPUT_CIRCUITS_SPARE VARCHAR(225),
				INSTALLED_EQUIPMENT_VULNARABLE  VARCHAR(225),
				CONSTRAINT PK_TESTING_DISTRIBUTION_ID PRIMARY KEY(DISTRIBUTION_ID),
				CONSTRAINT FK_DISTRIBUTION_TESTING_ID FOREIGN KEY (TESTING_ID) REFERENCES TESTING_TABLE(TESTING_ID) ON DELETE CASCADE     
				
	);
CREATE TABLE DISTRIBUTION_INCOMING_VALUE_TABLE (
                INCOMING_ID INT AUTO_INCREMENT,              
				DISTRIBUTION_ID INT,
		        INCOMING_VOLTAGE VARCHAR(225),
				INCOMING_ZS VARCHAR(225),
				INCOMING_IPF VARCHAR(225),
				CONSTRAINT PK_INCOMING_ID PRIMARY KEY(INCOMING_ID),
				CONSTRAINT FK_DISTRIBUTION_ID FOREIGN KEY (DISTRIBUTION_ID) REFERENCES TESTING_DISTRIBUTION_TABLE(DISTRIBUTION_ID) ON DELETE CASCADE     

	);

CREATE TABLE TESTING_CIRCUIT_TABLE ( 
                TESTING_CIRCUIT_ID INT AUTO_INCREMENT,
				TESTING_ID INT,
 				CIRCUIT_NO INT,
				DESCRIPTION VARCHAR(225),
				STANDARD_NO VARCHAR(225),
				TYPE VARCHAR(225),
				RATING INT,
				BREAKING_CAPACITY  INT,
				CONSTRAINT PK_TESTING_CIRCUIT_ID PRIMARY KEY(TESTING_CIRCUIT_ID),
				CONSTRAINT FK_CIRCUIT_TESTING_ID FOREIGN KEY (TESTING_ID) REFERENCES TESTING_TABLE(TESTING_ID) ON DELETE CASCADE              

 );


 CREATE TABLE TESTING_CONDUCTOR_TABLE ( 
                TESTING_CONDUCTOR_ID INT AUTO_INCREMENT,
				TESTING_ID INT,
 				INSTALLATION_REFERANCE_METHOD VARCHAR(225),
				LIVE INT,
				PE_CPC INT, 
				CONSTRAINT PK_TESTING_CONDUCTOR_ID PRIMARY KEY(TESTING_CONDUCTOR_ID),
				CONSTRAINT FK_CONDUCTOR_TESTING_CIRCUIT_ID FOREIGN KEY (TESTING_ID) REFERENCES TESTING_TABLE(TESTING_ID) ON DELETE CASCADE              

 );
  
CREATE TABLE TESTING_CONTINUITY_TABLE ( 
                TESTING_CONTINUITY_ID INT AUTO_INCREMENT,
				TESTING_ID INT,
 				APPROXIMATE_LENGTH INT,
				R1_R2  INT,
				R2  INT, 
				L_L INT, 
				L_E INT, 
				POLARITY VARCHAR(225), 
				CONSTRAINT PK_TESTING_CONTINUITY_ID PRIMARY KEY(TESTING_CONTINUITY_ID),
				CONSTRAINT FK_CONTINUITY_TESTING_ID FOREIGN KEY (TESTING_ID) REFERENCES TESTING_TABLE(TESTING_ID) ON DELETE CASCADE              

 );
 
CREATE TABLE TESTING_VOLTAGE_TABLE ( 
                TESTING_VOLTAGE_ID INT AUTO_INCREMENT,
				TESTING_ID INT,
 				R_Y VARCHAR(225),
				R_B VARCHAR(225),
				Y_B VARCHAR(225), 
				R_N VARCHAR(225), 
				Y_N VARCHAR(225), 
				B_N VARCHAR(225), 
				R_PE VARCHAR(225), 
				Y_PE VARCHAR(225), 
				B_PE VARCHAR(225), 
 				CONSTRAINT PK_TESTING_VOLTAGE_ID PRIMARY KEY(TESTING_VOLTAGE_ID),
				CONSTRAINT FK_VOLTAGE_TESTING_ID FOREIGN KEY (TESTING_ID) REFERENCES TESTING_TABLE(TESTING_ID) ON DELETE CASCADE              

 );
 
CREATE TABLE TESTING_LOOPIMPEDANCE_TABLE ( 
                TESTING_LOOPIMPEDANCE_ID INT AUTO_INCREMENT,
				TESTING_ID INT,
 				R_Y VARCHAR(225),
				R_B VARCHAR(225),
				Y_B VARCHAR(225), 
				R_N VARCHAR(225), 
				Y_N VARCHAR(225), 
				B_N VARCHAR(225), 
				R_PE VARCHAR(225), 
				Y_PE VARCHAR(225), 
				B_PE VARCHAR(225),  
				CONSTRAINT PK_TESTING_LOOPIMPEDANCE_ID PRIMARY KEY(TESTING_LOOPIMPEDANCE_ID),
				CONSTRAINT FK_LOOPIMPEDANCE_TESTING_ID FOREIGN KEY (TESTING_ID) REFERENCES TESTING_TABLE(TESTING_ID) ON DELETE CASCADE              
 
 );
 
 CREATE TABLE TESTING_FAULTCURRENT_TABLE ( 
                TESTING_FAULTCURRENT_ID INT AUTO_INCREMENT,
				TESTING_ID INT,
 				R_Y VARCHAR(225),
				R_B VARCHAR(225),
				Y_B VARCHAR(225), 
				R_N VARCHAR(225), 
				Y_N VARCHAR(225), 
				B_N VARCHAR(225), 
				R_PE VARCHAR(225), 
				Y_PE VARCHAR(225), 
				B_PE VARCHAR(225),  
				CONSTRAINT PK_TESTING_FAULTCURRENT_ID PRIMARY KEY(TESTING_FAULTCURRENT_ID),
				CONSTRAINT FK_FAULTCURRENT_TESTING_ID FOREIGN KEY (TESTING_ID) REFERENCES TESTING_TABLE(TESTING_ID) ON DELETE CASCADE              

 );
 
CREATE TABLE TESTING_DISCONNECTIONTIME_TABLE ( 
                TESTING_DISCONNECTIONTIME_ID INT AUTO_INCREMENT,
				TESTING_ID INT,
 				R_Y VARCHAR(225),
				R_B VARCHAR(225),
				Y_B VARCHAR(225), 
				R_N VARCHAR(225), 
				Y_N VARCHAR(225), 
				B_N VARCHAR(225), 
				R_PE VARCHAR(225), 
				Y_PE VARCHAR(225), 
				B_PE VARCHAR(225), 
 				CONSTRAINT PK_TESTING_DISCONNECTIONTIME_ID PRIMARY KEY(TESTING_DISCONNECTIONTIME_ID),
				CONSTRAINT FK_DISCONNECTIONTIME_TESTING_ID FOREIGN KEY (TESTING_ID) REFERENCES TESTING_TABLE(TESTING_ID) ON DELETE CASCADE              

 );
 
CREATE TABLE TESTING_RCD_TABLE ( 
                TESTING_RCD_ID INT AUTO_INCREMENT,
				TESTING_ID INT,
 				RCD_CURRENT INT,
				OPERATING_CURRENT  INT,
				OPERATING_FIVE_CURRENT  INT, 
				TEST_BUTTON_OPERATION VARCHAR(225), 
				REMARKS VARCHAR(225),
				CONSTRAINT PK_TESTING_RCD_ID PRIMARY KEY(TESTING_RCD_ID),
				CONSTRAINT FK_RCD_TESTING_ID FOREIGN KEY (TESTING_ID) REFERENCES TESTING_TABLE(TESTING_ID) ON DELETE CASCADE              

 );
 
 --> Part_5 Summary_Section

 CREATE TABLE SUMMARY_TABLE (
            SUMMARY_ID INT AUTO_INCREMENT,
			SITE_ID INT,
			USER_NAME VARCHAR(255),
            LIMITATIONS_INSPECTION  VARCHAR(255),
            EXTENT_INSTALLATION VARCHAR(255),
            AGREED_LIMITATIONS  VARCHAR(255),
            AGREED_WITH VARCHAR(255),
            OPERATIONAL_LIMITATIONS VARCHAR(255),
            INSPECTION_TESTING_DETAILED VARCHAR(255),
            RECOMMENDATIONS_DATE VARCHAR(255),
            GENERAL_CONDITION_INSTALLATION VARCHAR(500),
            OVERALL_ASSESSMENT_INSTALLATION VARCHAR(255),
            CREATED_DATE DATETIME,
            CONSTRAINT PK_SUMMARY_ID PRIMARY KEY(SUMMARY_ID)
              
);

CREATE TABLE OBSERVATIONS_TABLE (
            OBSERVATIONS_ID INT AUTO_INCREMENT,
			SUMMARY_ID INT,
            OBSERVATIONS  VARCHAR(255),
            REFERANCE_NUMBER_REPORT VARCHAR(255),
            FURTHER_ACTIONS  VARCHAR(255),
            COMMENT VARCHAR(255),
            CONSTRAINT PK_OBSERVATIONS_ID PRIMARY KEY(OBSERVATIONS_ID),
			CONSTRAINT FK_OBSERVATIONS_SUMMARY_ID FOREIGN KEY (SUMMARY_ID) REFERENCES SUMMARY_TABLE(SUMMARY_ID) ON DELETE CASCADE              
);

   CREATE TABLE DECLARATION_TABLE (
            DECLARATION_ID INT AUTO_INCREMENT,
			SUMMARY_ID INT,
            DECLARATION_ROLE  VARCHAR(255),
            NAME VARCHAR(255),
            SIGNATURE  VARCHAR(255),
            COMPANY VARCHAR(255),
            POSITION VARCHAR(255),
            ADDRESS VARCHAR(500),
            DATE VARCHAR(255),			
            CONSTRAINT PK_DECLARATION_ID PRIMARY KEY(DECLARATION_ID),
			CONSTRAINT FK_DECLARATION_SUMMARY_ID FOREIGN KEY (SUMMARY_ID) REFERENCES SUMMARY_TABLE(SUMMARY_ID) ON DELETE CASCADE              
);