name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: CapeSoftwareTeam/lv-inspection-safety-backend@master
      with:
      name: lv-safety-verification
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
    - name: Check Out Repo 
      uses: actions/checkout@v2
    - name: Build the Docker images
      run: docker-compose up -d
